// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNu8zTfrHmV20z670KN1cwFlMJALc79sQ',
    appId: '1:604005234166:web:327e341803b38e6e7743d7',
    messagingSenderId: '604005234166',
    projectId: 'flugo-chat',
    authDomain: 'flugo-chat.firebaseapp.com',
    databaseURL: 'https://flugo-chat-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmNVIS4PC01-nU-M0-OTpo1_1wACbHUGw',
    appId: '1:604005234166:android:46662354510bb9a47743d7',
    messagingSenderId: '604005234166',
    projectId: 'flugo-chat',
    databaseURL: 'https://flugo-chat-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCje42fUBqgO0luPAzaux7DkpCQEkkMuGg',
    appId: '1:604005234166:ios:724a231c432a72887743d7',
    messagingSenderId: '604005234166',
    projectId: 'flugo-chat',
    databaseURL: 'https://flugo-chat-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-chat.firebasestorage.app',
    iosBundleId: 'joao.romano.flugoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCje42fUBqgO0luPAzaux7DkpCQEkkMuGg',
    appId: '1:604005234166:ios:724a231c432a72887743d7',
    messagingSenderId: '604005234166',
    projectId: 'flugo-chat',
    databaseURL: 'https://flugo-chat-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-chat.firebasestorage.app',
    iosBundleId: 'joao.romano.flugoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNu8zTfrHmV20z670KN1cwFlMJALc79sQ',
    appId: '1:604005234166:web:14254cf25898feed7743d7',
    messagingSenderId: '604005234166',
    projectId: 'flugo-chat',
    authDomain: 'flugo-chat.firebaseapp.com',
    databaseURL: 'https://flugo-chat-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-chat.firebasestorage.app',
  );
}
